// t_turing.zig — Turing completeness demonstration for malbolge-free
//
// Brainfuck is Turing-complete. If we can compile BF → Malbolge and get
// identical output, Malbolge is TC by reduction.
//
// This test uses the Malbolge-Translator Zig generator (external) to compile
// BF "Hello World" to Malbolge, then runs it through malbolge-free core.

const std = @import("std");
const core = @import("malbolge_free.zig");
const MalbolgeCore = core.MalbolgeCore;

const BF_HELLO = "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.";

/// Minimal BF interpreter to get expected output
fn runBF(source: []const u8, allocator: std.mem.Allocator) ![]u8 {
    const TapeSize = 30_000;
    var tape: [TapeSize]u8 = undefined;
    @memset(tape[0..], 0);
    var ptr: usize = 0;
    var pc: usize = 0;
    var output = std.array_list.Managed(u8).init(allocator);
    errdefer output.deinit();

    // Bracket matching
    var bracket_map = std.AutoHashMap(usize, usize).init(allocator);
    errdefer bracket_map.deinit();
    var stack = std.array_list.Managed(usize).init(allocator);
    errdefer stack.deinit();

    for (source, 0..) |ch, i| {
        switch (ch) {
            '[' => try stack.append(i),
            ']' => {
                const match = stack.pop() orelse return error.UnmatchedBracket;
                try bracket_map.put(i, match);
                try bracket_map.put(match, i);
            },
            else => {},
        }
    }

    var steps: u64 = 0;
    while (pc < source.len) {
        steps += 1;
        if (steps > 10_000_000) return error.MaxStepsExceeded;

        switch (source[pc]) {
            '>' => ptr += 1,
            '<' => ptr -= 1,
            '+' => tape[ptr] += 1,
            '-' => tape[ptr] -= 1,
            '.' => try output.append(tape[ptr]),
            ',' => {}, // no input
            '[' => {
                if (tape[ptr] == 0) pc = bracket_map.get(pc).?;
            },
            ']' => {
                if (tape[ptr] != 0) pc = bracket_map.get(pc).?;
            },
            else => {},
        }
        pc += 1;
    }
    return try output.toOwnedSlice();
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;

    // 1. BF expected output
    const bf_output = try runBF(BF_HELLO, allocator);
    defer allocator.free(bf_output);
    std.debug.print("BF output: {s}\n", .{bf_output});

    // 2. Expected Malbolge source (pre-generated by Malbolge-Translator)
    // This is the output of generator.generar("Hello World!", 20)
    const malbolge_src: []const u8 = @embedFile("turing_malbolge_hello.mal");
    std.debug.print("Malbolge program: {d} cells\n", .{malbolge_src.len});

    // 3. Run through malbolge-free core
    var vm = MalbolgeCore.init(allocator, 10, 59049, .fixed);
    defer vm.deinit();
    try vm.load(malbolge_src);

    const result = try vm.run(2_000_000, &.{});
    // result.stdout is std.ArrayList(u8), managed by the allocator
    // We need to free the underlying slice
    defer allocator.free(result.stdout.items);

    std.debug.print("Malbolge status: {s}, steps: {d}\n", .{result.status, result.steps});
    std.debug.print("Malbolge output: {s}\n", .{result.stdout.items});

    // 4. Verify
    if (std.mem.eql(u8, bf_output, result.stdout.items)) {
        std.debug.print("\n✅ TURING COMPLETENESS: BF -> Malbolge compilation works\n", .{});
    } else {
        std.debug.print("\n❌ MISMATCH\n", .{});
        return error.OutputMismatch;
    }
}

const Error = error{
    UnmatchedBracket,
    MaxStepsExceeded,
    OutputMismatch,
};