//! F7 — THE witness. cross_3pow19.mal is 100% generated Malbolge. No host help.
//! Run it with the Free core at width=20 on unbounded memory and check whether
//! any touched address exceeds 3^19 during a LEGAL execution.

const std = @import("std");
const core = @import("malbolge_free.zig");
const MalbolgeCore = core.MalbolgeCore;

pub fn main() !void {
    const alloc = std.heap.page_allocator;

    // generated by evidence/gen_f7.py; third instruction fixed to '&'
    const src = "(&&" ++ "z" ** 200;

    for ([2]struct { w: u8, g: core.GrowthPolicy, name: []const u8 }{
        .{ .w = 20, .g = .fixed, .name = "w20_fixed" },
        .{ .w = 20, .g = .pad_to_padwidth, .name = "w20_pad" },
    }) |cfg| {
        var vm = MalbolgeCore.init(alloc, cfg.w, null, cfg.g);
        defer vm.deinit();
        try vm.load(src);
        const res = try vm.run(100_000, "");

        const boundary = std.math.pow(u128, 3, 19);
        std.debug.print(
            "cfg={s} status={s} steps={d} max_addr={d} boundary={d} crossed={} max_value={d} growth_events={d}\n",
            .{
                cfg.name,
                res.status,
                res.steps,
                res.max_addr_touched,
                boundary,
                res.max_addr_touched >= boundary,
                res.max_value,
                vm.stats.growth_events,
            },
        );
    }
}
