# Generates evidence/run_f4.zig with the corpus embedded from disk — no hand-typing.

import pathlib

CORPUS = pathlib.Path(r"C:\Development\ISyCo Git\malbolge-free\corpus\classic")
progs = []
for f in sorted(CORPUS.iterdir()):
    src = f.read_text(encoding="utf-8")
    zig_src = src.replace("\\", "\\\\").replace('"', '\\"')
    progs.append((f.name, zig_src))

body = ",\n    ".join(
    f'.{{ .name = "{name}", .src = "{zx}", .stdin = "" }}'
    for name, zx in progs
)

template = """//! F4 r1 — AUTO-GENERATED by evidence/gen_f4.py. Never hand-edit.
const std = @import("std");
const core = @import("malbolge_free.zig");
const MalbolgeCore = core.MalbolgeCore;

const MEM_3_10: u128 = 3 * 3 * 3 * 3 * 3 * 3 * 3 * 3 * 3 * 3;

const Program = struct { name: []const u8, src: []const u8, stdin: []const u8 };

const PROGRAMS = [_]Program{
    PROGRAMS_HERE,
};

pub fn main() !void {
    const alloc = std.heap.page_allocator;

    for (PROGRAMS) |p| {
        var vm = MalbolgeCore.init(alloc, 10, MEM_3_10, .fixed);
        defer vm.deinit();
        try vm.load(p.src);
        const res = try vm.run(2_000_000, p.stdin);

        var h = std.crypto.hash.sha2.Sha256.init(.{});
        h.update(res.stdout.items);
        var digest: [32]u8 = undefined;
        h.final(&digest);
        const hex = std.fmt.bytesToHex(digest, .lower);

        std.debug.print("program={s} status={s} steps={d} sha256={s} stdout_raw=[", .{ p.name, res.status, res.steps, hex });
        for (res.stdout.items) |ch| {
            std.debug.print("{x:0>2}", .{ch});
        }
        std.debug.print("] cells={d}\\n", .{res.cells_materialized});
    }
}
"""

template = template.replace("PROGRAMS_HERE", body)
out = pathlib.Path(r"C:\Development\ISyCo Git\malbolge-free\evidence\run_f4.zig")
out.write_text(template, encoding="utf-8")
print("wrote", out)
